#!/bin/bash
# ufetch-gentoo - tiny system info for Gentoo Linux

# System information
host=$(</etc/hostname)
os='Gentoo Linux'
kernel=$(uname -sr)
uptime=$(uptime -p | sed 's/up //')
packages=$(ls -d /var/db/pkg/*/* | wc -l)
shell=$(basename "$SHELL")

# User interface detection
get_ui() {
    for f in "$@"; do
        wm=$(tail -n 1 "$f" 2> /dev/null | awk '{print $2}')
        [ -n "$wm" ] && { echo "$wm"; return; }
    done
}

rcwm=$(get_ui "$HOME/.xinitrc" "$HOME/.xsession")

if [ -n "$DE" ]; then
    ui="$DE"
    uitype='DE'
elif [ -n "$WM" ]; then
    ui="$WM"
    uitype='WM'
elif [ -n "$XDG_CURRENT_DESKTOP" ]; then
    ui="$XDG_CURRENT_DESKTOP"
    uitype='DE'
elif [ -n "$DESKTOP_SESSION" ]; then
    ui="$DESKTOP_SESSION"
    uitype='DE'
elif [ -n "$rcwm" ]; then
    ui="$rcwm"
    uitype='WM'
elif [ -n "$XDG_SESSION_TYPE" ]; then
    ui="$XDG_SESSION_TYPE"
fi

ui=$(basename "$ui")

# Output with color formatting
echo
echo -e "\033[0;35m    .-----.      \033[0m$USER\033[0;35m@\033[0m$host"
echo -e "\033[0;35m  .\`    _  \`.    \033[0;35mOS:        \033[0m$os"
echo -e "\033[0;35m  \`.   (__)  \`.  \033[0;35mKERNEL:    \033[0m$kernel"
echo -e "\033[0;35m    \`.        /  \033[0;35mUPTIME:    \033[0m$uptime"
echo -e "\033[0;35m   .\`       .\`   \033[0;35mPACKAGES:  \033[0m$packages"
echo -e "\033[0;35m  /       .\`     \033[0;35mSHELL:     \033[0m$shell"
echo -e "\033[0;35m  \____.-\`       \033[0;35m$uitype:        \033[0m$ui"
echo
