#!/bin/bash
# ufetch-hyperbola - tiny system info for Hyperbola GNU/Linux-libre

# System information
host=$(</etc/hostname)
os='Hyperbola GNU/Linux-libre'
kernel=$(uname -sr)
uptime=$(uptime -p | sed 's/up //')
packages=$(pacman -Q | wc -l)
shell=$(basename "$SHELL")

# User interface detection
get_ui() {
    for f in "$@"; do
        wm=$(tail -n 1 "$f" 2> /dev/null | awk '{print $2}')
        [ -n "$wm" ] && { echo "$wm"; return; }
    done
}

rcwm=$(get_ui "$HOME/.xinitrc" "$HOME/.xsession")

if [ -n "$DE" ]; then
    ui="$DE"
    uitype='DE'
elif [ -n "$WM" ]; then
    ui="$WM"
    uitype='WM'
elif [ -n "$XDG_CURRENT_DESKTOP" ]; then
    ui="$XDG_CURRENT_DESKTOP"
    uitype='DE'
elif [ -n "$DESKTOP_SESSION" ]; then
    ui="$DESKTOP_SESSION"
    uitype='DE'
elif [ -n "$rcwm" ]; then
    ui="$rcwm"
    uitype='WM'
elif [ -n "$XDG_SESSION_TYPE" ]; then
    ui="$XDG_SESSION_TYPE"
fi

ui=$(basename "$ui")

## OUTPUT

cat <<EOF

${c0}      |\`__.\`/   ${nc}${USER}${ic}@${nc}${host}${reset}
${c0}      \____/    ${lc}OS:        ${ic}${os}${reset}
${c0}      .--.      ${lc}KERNEL:    ${ic}${kernel}${reset}
${c0}     /    \\     ${lc}UPTIME:    ${ic}${uptime}${reset}
${c0}    /  ___ \\    ${lc}PACKAGES:  ${ic}${packages}${reset}
${c0}   / .\`   \`.\\   ${lc}SHELL:     ${ic}${shell}${reset}
${c0}  /.\`      \`.\\  ${lc}${uitype}:        ${ic}${ui}${reset}

EOF
