#!/bin/sh
#
# ufetch-reactOS - tiny system info for reactOS
# built using mingw with bash 3.1


## INFO

# whoami is used since this isn't a unixsystem
host="$(whoami | sed -e 's/\(.*\)/\U\1/')"
os="ReactOS"	# I don't have a clever tagline here
kernel="$(uname -sr)"
uptime="$(uptime | sed -n 's/.* up \(.\+\?\),\s\s.*,\s\s.*/\1/p; s/System Up Time:\s\+//p')"
shell="$(basename ${SHELL})"

## DEFINE COLORS

# probably don't change these
if [ -x "$(command -v tput)" ]; then
	bold="$(tput bold)"
	black="$(tput setaf 0)"
	red="$(tput setaf 1)"
	green="$(tput setaf 2)"
	yellow="$(tput setaf 3)"
	blue="$(tput setaf 4)"
	magenta="$(tput setaf 5)"
	cyan="$(tput setaf 6)"
	white="$(tput setaf 7)"
	reset="$(tput sgr0)"
fi

# you can change these
lc="${reset}${bold}${black}"		# labels
nc="${reset}${bold}${black}"		# user and hostname
ic="${reset}${bold}${white}"		# info
c0="${reset}${bold}${black}"		# first color
c1="${reset}${white}"			# second color
c2="${reset}${yellow}"			# third color

## OUTPUT

cat <<EOF
   /-/\__/\-\   ${USER}${ic}${nc}${host}${reset}
   \/  \/  \/   ${lc}OS:        ${ic}${os}${reset}
    \   \  /    ${lc}KERNEL:    ${ic}${kernel}${reset}
    |\	 \/|    ${lc}UPTIME:    ${ic}${uptime}${reset}
   /|/\   \|\   ${lc}SHELL:     ${ic}${shell}${reset}
  / /  \   \ \  ${reset}
 / /   /\   \ \ ${reset}
 |/   /__\   \| ${reset}
 \   /    \   / ${reset}
  \-/      \-/  ${reset}
  
EOF
