#!/bin/bash
# ufetch-openbsd - tiny system info for OpenBSD

# System information
host=$(hostname)
os=$(uname -sr)
kernel=$(uname -v)
uptime=$(uptime | awk -F, '{sub(".*up ",x,$1);print $1}' | sed -e 's/^[ \t]*//')
packages=$(ls -d /var/db/pkg/* | wc -l | sed -e 's/^[ \t]*//')
shell=$(basename "$SHELL")

# User interface detection
get_ui() {
    for f in "$@"; do
        wm=$(tail -n 1 "$f" 2> /dev/null | awk '{print $2}')
        [ -n "$wm" ] && { echo "$wm"; return; }
    done
}

rcwm=$(get_ui "$HOME/.xinitrc" "$HOME/.xsession")

if [ -n "$DE" ]; then
    ui="$DE"
    uitype='DE'
elif [ -n "$WM" ]; then
    ui="$WM"
    uitype='WM'
elif [ -n "$XDG_CURRENT_DESKTOP" ]; then
    ui="$XDG_CURRENT_DESKTOP"
    uitype='DE'
elif [ -n "$DESKTOP_SESSION" ]; then
    ui="$DESKTOP_SESSION"
    uitype='DE'
elif [ -n "$rcwm" ]; then
    ui="$rcwm"
    uitype='WM'
elif [ -n "$XDG_SESSION_TYPE" ]; then
    ui="$XDG_SESSION_TYPE"
fi

ui=$(basename "$ui")

# Output with color formatting
echo
echo -e "\033[0;33m       _____      \033[0m$USER\033[0;33m@\033[0m$host"
echo -e "\033[0;33m     \-     -/    \033[0;33mOS:        \033[0m$os"
echo -e "\033[0;33m  \_/         \   \033[0;33mKERNEL:    \033[0m$kernel"
echo -e "\033[0;33m  |        \033[0;37mO O \033[0;33m|  \033[0;33mUPTIME:    \033[0m$uptime"
echo -e "\033[0;33m  |_  \033[0;33m<   \033[0;37m)  \033[0;33m3 \033[0;33m)  \033[0;33mPACKAGES:  \033[0m$packages"
echo -e "\033[0;33m  / \         /   \033[0;33mSHELL:     \033[0m$shell"
echo -e "\033[0;33m     /-_____-\    \033[0;33m$uitype:        \033[0m$ui"
echo
